// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmlagyrpyoaekarahtxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbGFneXJweW9hZWthcmFodHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzA2NDUsImV4cCI6MjA3NjcwNjY0NX0.-WU3eU0KgLkM0ZOaVU_byMBxHwGBcdHgGkghz-wP3k4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});